# 🐳 DOCKER COMPOSE PRODUCTION - ENTERPRISE GRADE
version: '3.9'

services:
  # ============================================
  # Web Application
  # ============================================
  web:
    build:
      context: .
      dockerfile: Dockerfile.optimized
      args:
        NODE_ENV: production
    image: politica-argentina:latest
    container_name: politica-argentina-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL:-mysql://root:password@db:3306/politica_argentina}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./public:/app/public:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.politicaargentina.service=web"
      - "com.politicaargentina.version=3.0.0"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ============================================
  # MySQL Database
  # ============================================
  db:
    image: mysql:8.0
    container_name: politica-argentina-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=politica_argentina
      - MYSQL_USER=politica_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    labels:
      - "com.politicaargentina.service=database"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ============================================
  # Redis Cache (Opcional)
  # ============================================
  redis:
    image: redis:7-alpine
    container_name: politica-argentina-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    labels:
      - "com.politicaargentina.service=cache"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  # ============================================
  # Nginx Reverse Proxy (Opcional)
  # ============================================
  nginx:
    image: nginx:alpine
    container_name: politica-argentina-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - web
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "com.politicaargentina.service=proxy"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ============================================
# Networks
# ============================================
networks:
  app-network:
    driver: bridge
    name: politica-argentina-network

# ============================================
# Volumes
# ============================================
volumes:
  db-data:
    name: politica-argentina-db-data
    driver: local
  redis-data:
    name: politica-argentina-redis-data
    driver: local
  nginx-logs:
    name: politica-argentina-nginx-logs
    driver: local
