# nixpacks.toml
# Configuración optimizada para Railway

nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
# Solo construir el backend
cmds = ["pnpm build:backend"]

[start]
cmd = "node dist/index.js"
