[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build:backend"]

[start]
cmd = "node dist/server.js"

[variables]
NODE_ENV = "production"
