name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Use pnpm
        run: corepack prepare pnpm@10.19.0 --activate

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm check

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test


